branch-defaults:
  default:
    environment: Makingusefulstuff-env
  master:
    environment: Makingusefulstuff-env
environment-defaults:
  Makingusefulstuff-env:
    branch: null
    repository: null
global:
  application_name: MakingUsefulStuff
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
